# Generated by Django 4.1.7 on 2023-06-24 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mychatapp', '0003_chatmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='msg_reciever',
            new_name='msg_receiver',
        ),
    ]
